### ISSUE TITLE
the absence of a comma and a space between the codec and the track language in track-menu.lua

### ISSUE THREAD

**Issue by AdventurerRussia** [dyphire/mpv-scripts#1]
I noticed that there is no comma between the language and the codec of the track, although other data is separated by a comma, my inner perfectionist is indignant.
is it still possible to add a path mapping to external files?

![image](https://user-images.githubusercontent.com/14019010/200110918-33800981-fd5e-4df7-928c-efe8588c58cf.png)
I wanted to ask if it is possible to change the colors of these elements? I didn't find the settings to change them
![image](https://user-images.githubusercontent.com/14019010/200111007-6087ba30-c8f4-41d4-aa77-f7cfd40fca20.png)
and what are these functions? [%cursor%/%total%]
does it look broken?
![image](https://user-images.githubusercontent.com/14019010/200111511-b39e742d-0f3b-4c0e-866d-62e7026eef3b.png)

about fix-avsync.lua
the script works, but when you switch the track, the sound creaks, breaks for half a second, is it possible to fix it, for example, by silencing the track for 1 second between switching?

about open_dialog.lua 
is it possible to make it so that by selecting an external track, it immediately becomes the default in the player?

**Comment by dyphire** [comment]
> about fix-avsync.lua
the script works, but when you switch the track, the sound creaks, breaks for half a second, is it possible to fix it, for example, by silencing the track for 1 second between switching?
about open_dialog.lua
is it possible to make it so that by selecting an external track, it immediately becomes the default in the player?

It has been implemented in the latest [commit](https://github.com/dyphire/mpv-scripts/commit/56c85b02d3a29d2e432de036f9040ded2dac31c9), please test whether it works for you.

> and what are these functions? [%cursor%/%total%]
does it look broken?

It works fine on my end, make sure you are using the latest script of [adevice-list.lua](https://github.com/dyphire/mpv-scripts/blob/main/adevice-list.lua) and [scroll-list.lua](https://github.com/CogentRedTester/mpv-scroll-list/blob/master/scroll-list.lua).

**Comment by dyphire** [comment]
> I noticed that there is no comma between the language and the codec of the track, although other data is separated by a comma, my inner perfectionist is indignant.

The codec is a special property, so I won't choose to separate it with a comma. 
I added a [commit](https://github.com/dyphire/mpv-scripts/commit/1e6275b1882f3c6a505c1a3a50ec6cb39f029d7e) to separate it with a space, which is also the behavior of mpc-hc.
> is it still possible to add a path mapping to external files?

I didn't understand what you were trying to say.

> I wanted to ask if it is possible to change the colors of these elements? I didn't find the settings to change them.

This is possible, refer to [scroll-list.lua](https://github.com/CogentRedTester/mpv-scroll-list/blob/72a23966760641b89d5b73e44cd8a4d9b4884884/scroll-list.lua#L4-L8).
But at present, I have no plan to implement it.

**Comment by AdventurerRussia** [comment]
> 

well, for example, an external track, and so that the path to it is displayed in the system,
![image](https://user-images.githubusercontent.com/14019010/200121001-51696653-4993-46de-941d-440b920254ee.png)
something like this
This is possible, refer to [scroll-list.lua](https://github.com/CogentRedTester/mpv-scroll-list/blob/72a23966760641b89d5b73e44cd8a4d9b4884884/scroll-list.lua#L4-L8).
okay thanks

**Comment by dyphire** [comment]
> > 
> 
> well, for example, an external track, and so that the path to it is displayed in the system, something like this 
![image](https://user-images.githubusercontent.com/14019010/200121001-51696653-4993-46de-941d-440b920254ee.png) 

Now I understand your request, but I won't implemente it. Because too long string will cause unreadable and the osd overflow.
In order to avoid too long strings as much as possible, I have tried to split the filename in the tracktitle. 
https://github.com/dyphire/mpv-scripts/blob/fc04cabb722fff01cce1fa0d5a4f40b23307e556/track-list.lua#L202-L205
Implementing the functions you require will undermine my previous efforts.

**Comment by AdventurerRussia** [comment]
> > > 
> > 
> > 
> > well, for example, an external track, and so that the path to it is displayed in the system, something like this
> > ![image](https://user-images.githubusercontent.com/14019010/200121001-51696653-4993-46de-941d-440b920254ee.png)
> 
> Now I understand your request, but I won't implemente it. Because too long string will cause unreadable and the osd overflow. In order to avoid too long strings as much as possible, I have tried to split the filename in the tracktitle.
> 
> https://github.com/dyphire/mpv-scripts/blob/fc04cabb722fff01cce1fa0d5a4f40b23307e556/track-list.lua#L202-L205
> 
> 
> Implementing the functions you require will undermine my previous efforts.

thank you again very much for your work and for answering my questions, my requests should not be entered into the main code, these are just my preferences, but thank you again for pointing out how to do what I need.
