### ISSUE TITLE
open_dialog.lua after closing the player and opening it does not remember the audio track

### ISSUE THREAD

**Issue by AdventurerRussia** [dyphire/mpv-scripts#2]
that is, you closed the player and opened it, and your player opens without a sound track already, although in my opinion it should either remember the connected track through your script, or when launching, connect the last track before connecting with your script
but the script exposes just a video without sound

![image](https://user-images.githubusercontent.com/14019010/202854554-173b1226-f160-46c7-aeaf-e774f6009efd.png)

the video itself https://youtu.be/AkwSAhq8EPs

**Comment by dyphire** [comment]
The reason for this issue is that you may using `watch-later-options=aid` in mpv.conf.
The open_dialog.lua does not save the path of subtitles and audio tracks, which exceeds its expected function.
The real issue is that the option of `watch-later-options` does not support these properties of `audio-file-paths`, `sub-file-paths`, `audio-add` and `sub-add`.

**Comment by AdventurerRussia** [comment]
this is of course sad, except to force the script to enter its history log where all the paths are written.
