### ISSUE TITLE
fix-avsync frames jump back and forth when switching between videos

### ISSUE THREAD

**Issue by AdventurerRussia** [dyphire/mpv-scripts#9]
mpv v0.35.1
https://www.youtube.com/watch?v=mtd6W4BEAbg
at 31 seconds, it is very clearly visible when I switch the video frames jump.

**Comment by dyphire** [comment]
In fact, this issue is very difficult to fix. because the working principle of this script is to fix A/V sync by use `frame-step` and `frame-back`. So sometimes you will see obvious frame jumps.

On the other hand, mpv has fixed the related issue: https://github.com/mpv-player/mpv/issues/9591. This script is retained for the following reasons:
- mpv still stutters for about 1 second when switching audio tracks
- for users of older versions of mpv

**Comment by dyphire** [comment]
Cloesd by https://github.com/dyphire/mpv-scripts/commit/d6d759c3374072337a7e101122f60df939937bcc
